version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: food_delivery_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: food_delivery

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: food_delivery_api
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      MONGODB_URL: mongodb://mongodb:27017/food_delivery
      PORT: 5000
      NODE_ENV: production
    depends_on:
      - mongodb
    volumes:
      - ./backend/src/uploads:/app/src/uploads

  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    container_name: food_delivery_admin
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

  restaurant-panel:
    build:
      context: ./restaurant-panel
      dockerfile: Dockerfile
    container_name: food_delivery_restaurant
    restart: unless-stopped
    ports:
      - "5174:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
