module.exports = {
  User: require('./User'),
  Restaurant: require('./Restaurant'),
  RestaurantTiming: require('./RestaurantTiming'),
  RestaurantGallery: require('./RestaurantGallery'),
  RestaurantCategory: require('./RestaurantCategory'),
  FoodCategory: require('./FoodCategory'),
  Food: require('./Food'),
  FoodVariant: require('./FoodVariant'),
  Addon: require('./Addon'),
  Coupon: require('./Coupon'),
  Cart: require('./Cart'),
  Address: require('./Address'),
  Order: require('./Order'),
  OrderItem: require('./OrderItem'),
  Wishlist: require('./Wishlist'),
  FavoriteRestaurant: require('./FavoriteRestaurant'),
  Review: require('./Review'),
  Rating: require('./Rating'),
  Notification: require('./Notification'),
  Banner: require('./Banner'),
  Offer: require('./Offer'),
  Payment: require('./Payment'),
  DeliveryPartner: require('./DeliveryPartner'),
  Wallet: require('./Wallet'),
  Withdraw: require('./Withdraw'),
  Setting: require('./Setting'),
};
